apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-pv
  labels:
    app: songs-service
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/songs-service
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-pvc
  namespace: k8s-program
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# PersistentVolumes for databases
apiVersion: v1
kind: PersistentVolume
metadata:
  name: resources-db-pv-0
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/resources-db-0
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-db-pv-0
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/songs-db-0
    type: DirectoryOrCreate
